# fly.toml app configuration file generated for marstan on 2024-02-23T20:05:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marstan'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  hard_limit = 25 soft_limit = 20 type = "connections"
  handlers = ["http"] 
  port = 80
  handlers = ["tls", "http"] 
  port = 443

[[vm]]
  size = 'shared-cpu-1x'