# fly.toml app configuration file generated for marstan on 2024-02-24T05:39:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marstan'
primary_region = 'hkg'
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443 

[[vm]]
  size = 'shared-cpu-1x'
