# fly.toml app configuration file generated for comp7940-lab4 on 2024-02-21T20:43:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-lab4'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[service]]
  internal_port = 8080
  protocol = "tcp"
  
  [service.comcurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.port]]
    handlers = ["tls", "https"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
